export const AUTHENTICATED_ADMIN_TRUE = 'AUTHENTICATED_ADMIN_TRUE';
export const AUTHENTICATED_ADMIN_FALSE = 'AUTHENTICATED_ADMIN_FALSE';
export const UPDATED_PRODUCT_TRUE = 'UPDATED_PRODUCT_TRUE';
export const DELETED_PRODUCT_TRUE = 'DELETED_PRODUCT_TRUE';
export const CREATED_PRODUCT_TRUE = 'CREATED_PRODUCT_TRUE';
export const OPERATIONS_PRODUCT_FALSE = "OPERATIONS_PRODUCT_FALSE";
