export const AUTHENTICATED_TRUE = 'AUTHENTICATED_TRUE';
export const AUTHENTICATED_FALSE = 'AUTHENTICATED_FALSE';
export const UPDATED_TRUE = 'UPDATED_TRUE';
export const DELETED_TRUE = 'DELETED_TRUE';
export const CREATED_TRUE = 'CREATED_TRUE';
export const OPERATIONS_FALSE = "OPERATIONS_FALSE";
